spring:
  profiles:
    active: mem
  application:
    name: account
  config:
    import: optional:configserver:/
  cloud:
    config:
      username: username
      password: password
      profile: mem
      discovery:
        enabled: true
        serviceId: config-server
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: "*"