spring:
  application:
    name: account
  config:
    import: optional:configserver:/
  cloud:
    config:
      profile: dev
      discovery:
        enabled: true
        serviceId: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/