spring:
  config:
    import: optional:file:.env[.properties]
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native
  security:
    user:
      name: ${SERVICE_USERNAME}
      password: ${CONFIG_SERVICE_PASSWORD}
server:
  port: 8888