spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:/
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org:
      springframework:
        core:
          env: DEBUG
