spring:
  profiles:
    active: prod
  application:
    name: auth-service
  config:
    import: optional:configserver:/
  cloud:
    config:
      profile: prod
      username: username
      password: password
      discovery:
        enabled: true
        serviceId: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL:http://localhost:8761/eureka/}
      registryFetchIntervalSeconds: 1
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: localhost
logging:
  level:
    org:
      springframework:
        core:
          env: DEBUG
        security: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
