spring:
  profiles:
    active: dev
  application:
    name: auth-service
  config:
    import: optional:configserver:/
  cloud:
    config:
      profile: dev
      username: username
      password: password
      discovery:
        enabled: true
        serviceId: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
      prefer-ip-address: true
logging:
  level:
    org:
      springframework:
        core:
          env: DEBUG
