dist: trusty
services:
- docker
language: java
addons:
  apt:
    package:
    - openjdk-21-jdk
jdk: openjdk21
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

#TAG
  - export TAG=`if ["$TRAVIS_BRANCH" == "master"]; then echo "latest"; else echo $TRAVIS_BRANCH; fi"`
#SERVICE'S NAMES
  - export CONFIG_SERVER=dmsosa/dmservices-config-server
  - export SERVICE_REGISTRY=dmsosa/dmservices-service-registry
  - export ACCOUNT=dmsosa/dmservices-account
  - export NOTI=dmsosa/dmservices-noti
  - export STATS=dmsosa/dmservices-stats
  - export GATEWAY=dmsosa/dmservices-gateway
  - export AUTH_SERVICE=dmsosa/dmservices-auth-service
  - export POSTGRES_DB=dmsosa/dmservices-postgresql
#BUILD, TAG AND PUSH
#  POSTGRES IMAGE
  - docker build -t $POSTGRES_DB:$COMMIT ./postgresql
  - docker tag $POSTGRES_DB:$COMMIT $POSTGRES_DB:$TAG
  - docker push $POSTGRES_DB
#SERVICE REGISTRY IMAGE
  - docker build -t $SERVICE_REGISTRY:$COMMIT ./service-registry
  - docker tag $SERVICE_REGISTRY:$COMMIT $SERVICE_REGISTRY:$TAG
  - docker push $SERVICE_REGISTRY
#CONFIG SERVER IMAGE
  - docker build -t $CONFIG_SERVER:$COMMIT ./config-server
  - docker tag $CONFIG_SERVER:$COMMIT $CONFIG_SERVER:$TAG
  - docker push $CONFIG_SERVER
#GATEWAY IMAGE
  - docker build -t $GATEWAY:$COMMIT ./gateway
  - docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
  - docker push $GATEWAY
#AUTH_SERVICE IMAGE
  - docker build -t $AUTH_SERVICE:$COMMIT ./auth-service
  - docker tag $AUTH_SERVICE:$COMMIT $AUTH_SERVICE:$TAG
  - docker push $AUTH_SERVICE
#ACCOUNT IMAGE
  - docker build -t $ACCOUNT:$COMMIT ./account
  - docker tag $ACCOUNT:$COMMIT $ACCOUNT:$TAG
  - docker push $ACCOUNT
#STATS IMAGE
  - docker build -t $STATS:$COMMIT ./stats
  - docker tag $STATS:$COMMIT $STATS:$TAG
  - docker push $STATS
#NOTI IMAGE
  - docker build -t $NOTI:$COMMIT ./noti
  - docker tag $NOTI:$COMMIT $NOTI:$TAG
  - docker push $NOTI