services:
#config
  config-server:
    depends_on:
      service-registry:
        condition: service_healthy
    environment:
      SERVICE_REGISTRY_URL: http://service-registry:8761/eureka/
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: config-server
    build: config-server
    ports:
      - 8888:8888
  service-registry:
    container_name: service-registry
    build: service-registry
    ports:
      - 8761:8761
  auth-service:
    depends_on:
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    environment:
      SERVICE_REGISTRY_URL: ${SERVICE_REGISTRY_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: authdb
    container_name: auth-service
    build: auth-service
    ports:
      - 9000:9000
  gateway:
    depends_on:
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    environment:
      SERVICE_REGISTRY_URL: ${SERVICE_REGISTRY_URL}
    container_name: gateway
    build: gateway
    ports:
      - 8061:8061
#services
  account:
    depends_on:
      auth-service:
        condition: service_healthy
    environment:
      SERVICE_REGISTRY_URL: ${SERVICE_REGISTRY_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: accountdb
    container_name: account
    build: account
    ports:
      - 8083:8083
  stats:
    depends_on:
      auth-service:
        condition: service_healthy
    environment:
      SERVICE_REGISTRY_URL: ${SERVICE_REGISTRY_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: statsdb
    container_name: stats
    build: stats
    ports:
      - 8085:8085
  noti:
    depends_on:
      auth-service:
        condition: service_healthy
    environment:
      SERVICE_REGISTRY_URL: ${SERVICE_REGISTRY_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: notidb
    container_name: noti
    build: noti
    ports:
      - 8084:8084
#database a single PG container with all the databases for the microservices
  dmservices-database:
    container_name: dmservices-database
    build: postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5000:5432
volumes:
  dmservicesvol: