services:
  postgresql:
    image: dmsosa/postgres
    restart: always
    environment:
      - PG_USER=user
      - POSTGRES_PASSWORD=password
    ports:
     - 5000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/my-secret
    image: dpage/pgadmin4:latest
    secrets:
      - my-secret
    ports:
      - 5051:80
secrets:
  my-secret:
    file: dbsecrets.txt