services:
  config-server:
    depends_on:
      service-registry:
        condition: service_healthy
    environment:
      SERVICE_REGISTRY_URL: ${SERVICE_REGISTRY_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      HOSTNAME: ${HOSTNAME}
    container_name: config-server
    build: config-server
    expose:
      - "8888"
    ports:
      - 127.0.0.1:8888:8888
    networks:
      - dmnetwork
  service-registry:
    container_name: service-registry
    build: service-registry
    expose:
      - "8761"
    ports:
      - 127.0.0.1:8761:8761
    networks:
      - dmnetwork
  auth-service:
    depends_on:
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    environment:
      SERVICE_REGISTRY_URL: ${SERVICE_REGISTRY_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: authdb
      HOSTNAME: ${HOSTNAME}
    container_name: auth-service
    build: auth-service
    expose:
      - "9000"
    ports:
      - 127.0.0.1:9000:9000
    networks:
      - dmnetwork
  gateway:
    depends_on:
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    environment:
      SERVICE_REGISTRY_URL: ${SERVICE_REGISTRY_URL}
      HOSTNAME: ${HOSTNAME}
    container_name: gateway
    build: gateway
    expose:
      - "8061"
    ports:
      - 127.0.0.1:8061:8061
    networks:
      - dmnetwork
#micro services
  account:
    depends_on:
      auth-service:
        condition: service_healthy
    environment:
      SERVICE_REGISTRY_URL: ${SERVICE_REGISTRY_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: accountdb
      HOSTNAME: ${HOSTNAME}
    container_name: account
    build: account
    expose:
      - "8083"
    ports:
      - 127.0.0.1:8083:8083
    networks:
      - dmnetwork
  stats:
    depends_on:
      auth-service:
        condition: service_healthy
    environment:
      SERVICE_REGISTRY_URL: ${SERVICE_REGISTRY_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: statsdb
      HOSTNAME: ${HOSTNAME}
    container_name: stats
    build: stats
    expose:
      - "8085"
    ports:
      - 127.0.0.1:8085:8085
    networks:
      - dmnetwork
  noti:
    depends_on:
      auth-service:
        condition: service_healthy
    environment:
      SERVICE_REGISTRY_URL: ${SERVICE_REGISTRY_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: notidb
      HOSTNAME: ${HOSTNAME}
    container_name: noti
    build: noti
    expose:
      - "8084"
    ports:
      - 127.0.0.1:8084:8084
    networks:
      - dmnetwork
  #database a single PG container with all the databases for the microservices
  dmservices-database:
    container_name: dmservices-database
    build: postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5000"
    ports:
      - 127.0.0.1:5000:5432
    networks:
      - dmnetwork
volumes:
  dmservicesvol:
networks:
  dmnetwork:
    name: dmnetwork
    external: true