server:
  port: 7099
api:
  security:
    token:
      secret: ${JWT_SECRET:secret}
  issuer: ${JWT_ISSUER:myessen}

logging:
  level:
    org:
      springframework:
        security: TRACE
spring:
  datasource:
    url: ${PG_URL}/${PG_BLOG_DATABASE}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
management:
  tracing:
    sampling:
      probability: 1.0