application:
  name: myessen
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
server:
  port: 8082
spring:
  datasource:
    password: pepeeselmejor
    url: jdbc:postgresql://localhost:5432/myessen
    username: postgres
springdoc:
  api-docs:
    enabled: true
  show-actuator: true
  swagger-ui:
    path: /swagger-ui.html
management:
  tracing:
    sampling:
      probability: 1.0