server:
  port:
    8061
management:
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - RewritePath=/api/v1/.*?/(?<remaining>.*), /$\{remaining}
      routes:
        - id: tool-service
          predicates:
            - Path=/api/v1/tool/**
          uri: lb://tool-service
        - id: myessen-service
          predicates:
            - Path=/api/v1/myessen/**
          uri: lb://myessen-service
