server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
flyway:
  locations: classpath:db/migration
  schema: myessen
spring:
  datasource:
    password: pepeeselmejor
    url: jdbc:postgresql://localhost:5432/myessen
    username: postgres
springdoc:
  api-docs:
    enabled: true
  show-actuator: true
  swagger-ui:
    path: /swagger-ui.html
management:
  tracing:
    sampling:
      probability: 1.0