server:
  port: 8081
application:
  secret-key: ${JWT_SECRET:mysecretkey}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
flyway:
  locations: classpath:db/migration
  schema: myessen
logging:
  level:
    org:
      springframework:
        security: TRACE
spring:
  datasource:
    password: pepeeselmejor
    url: jdbc:postgresql://localhost:5432/vuttr
    username: postgres
springdoc:
  api-docs:
    enabled: false
  show-actuator: true
  swagger-ui:
    url: /vuttr.yaml
