spring:
  profiles:
    active: mem
  application:
    name: gateway
  config:
    import: optional:configserver:/
  cloud:
    config:
      profile: dev
      username: username
      password: password
      discovery:
        enabled: true
        serviceId: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

