spring:
  profiles:
    active: dev
  application:
    name: gateway
  config:
    import: optional:configserver:/
  cloud:
    config:
      profile: dev
      username: username
      password: password
      discovery:
        enabled: true
        serviceId: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true