spring:
  profiles:
    active: dev
  application:
    name: noti
  config:
    import: optional:configserver:/
  cloud:
    config:
      username: username
      password: password
      profile: dev
      discovery:
        enabled: true
        serviceId: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
