spring:
  profiles:
    active: mem
  application:
    name: auth-service
  config:
    import: optional:configserver:/
  cloud:
    config:
      profile: mem
      username: username
      password: password
      discovery:
        enabled: true
        serviceId: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
logging:
  level:
    org:
      springframework:
        core:
          env: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
