spring:
  profiles:
    active: dev
  application:
    name: stats
  config:
    import: optional:configserver:/
  cloud:
    config:
      username: username
      password: password
      profile: dev
      discovery:
        enabled: true
        serviceId: config-server
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "refresh"
