spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native
  security:
    user:
      name: ${SERVICE_USERNAME:username}
      password: ${CONFIG_SERVICE_PASSWORD:password}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888