server:
  servlet:
    context-path: /api/account
  port: 8083

spring:
  profile: dev
  security:
    oauth2:
      resource:
        loadBalanced: true
        jwt:
          issuer-uri: http://auth-service/api/auth
#      resource-server:
#        jwt:
#          issuer-uri: http://auth-service
      client:
        provider:
          auth:
            issuer-uri: http://localhost:7099/api/uaa
        registration:
          accountClient:
            provider: auth
            client-id: accountClient
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid,profile
            client-name: account
  datasource:
    url: jdbc:h2:mem:demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true


logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG