server:
  servlet:
    context-path: /api/account
  port: 8083

spring:
  profile: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7099/api/auth
      client:
        clientId: account
        clientSecret: secret
        accessTokenUri: http://localhost:7099/api/auth/oauth2/token
        grant-type: client_credentials
        scope: server
  datasource:
    url: jdbc:h2:mem:demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true


logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG