spring:
  profile: prod
  datasource:
    url: jdbc:postgresql://accountpg:5432
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
server:
  port: 8083
