database: h2

server:
  servlet:
    context-path: /api/uaa
  port: 9000
api:
  security:
    token:
      secret: ${JWT_SECRET:secret}
  issuer: ${JWT_ISSUER:myessen}
logging:
  level:
    org:
      springframework:
        security: TRACE
spring:
  profile: dev
# the RegisteredClientRepository is configured programmatically
  security:
    oauth2:
      resource-server:
        issuer-uri: http://localhost:9000/api/uaa
  flyway:
    user: sa
    password: password
    url: jdbc:h2:mem:demo
    locations: classpath:db/migration/${database}
  datasource:
    url: jdbc:h2:mem:demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false
  devtools:
    restart:
      exclude: /static/**,/templates/**
    livereload:
      port: 35730