spring:
  profiles:
    active: "dev"
server:
  port: 7099
api:
  security:
    token:
      secret: ${JWT_SECRET:secret}
  issuer: ${JWT_ISSUER:myessen}
logging:
  level:
    org:
      springframework:
        security: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
management:
  tracing:
    sampling:
      probability: 1.0
---
spring:
  profile: dev
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:file:/./data/demo
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

---

#spring:
#  profile: prod
#  datasource:
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: pepeeselmejor
#    url: jdbc:postgresql://localhost/postgres
