server:
  servlet:
    context-path: /api/uaa
  port: 9000
api:
  security:
    token:
      secret: ${JWT_SECRET:secret}
  issuer: ${JWT_ISSUER:myessen}
logging:
  level:
    org:
      springframework:
        security: TRACE
spring:
  profile: mem
# the RegisteredClientRepository is configured programmatically
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:demo
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true


