server:
  servlet:
    context-path: /api/uaa
  port: 9000
api:
  security:
    token:
      secret: ${JWT_SECRET:secret}
  issuer: ${JWT_ISSUER:myessen}
logging:
  level:
    org:
      springframework:
        security: TRACE
spring:
  profile: prod
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    #    using the container’s name as hostname
    url: jdbc:postgresql://dmservices-database:5432/${POSTGRES_DB}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
