server:
  servlet:
    context-path: /api/uaa
  port: 9000
api:
  security:
    token:
      secret: ${JWT_SECRET:secret}
  issuer: ${JWT_ISSUER:myessen}
logging:
  level:
    org:
      springframework:
        security: TRACE
spring:
  profile: dev
# the RegisteredClientRepository is configured programmatically
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: pepeeselmejor
    url: jdbc:postgresql://localhost:5432/dmsosa
  thymeleaf:
    cache: false
  devtools:
    restart:
      exclude: /static/**,/templates/**
    livereload:
      port: 35730