server:
  port: 7099
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: pepeeselmejor
    url: jdbc:postgresql://localhost/postgres
api:
  security:
    token:
      secret: ${JWT_SECRET:secret}
  issuer: ${JWT_ISSUER:myessen}
logging:
  level:
    org:
      springframework:
        security: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
management:
  tracing:
    sampling:
      probability: 1.0
