server:
  servlet:
    context-path: /api/uaa
  port: 7099
api:
  security:
    token:
      secret: ${JWT_SECRET:secret}
  issuer: ${JWT_ISSUER:myessen}
logging:
  level:
    org:
      springframework:
        security: TRACE
management:
  tracing:
    sampling:
      probability: 1.0
spring:
  profiles: dev
# the RegisteredClientRepository is configured programmatically
  datasource:
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#    url: jdbc:h2:mem:demo
    driverClassName: org.postgresql.Driver
    username: postgres
    password: pepeeselmejor
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true


