spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
#    using the container’s name as hostname
    url: jdbc:postgres://authpg:5432
server:
  port: 7099
api:
  security:
    token:
      secret: ${JWT_SECRET:secret}
  issuer: ${JWT_ISSUER:myessen}
logging:
  level:
    org:
      springframework:
        security: TRACE
management:
  tracing:
    sampling:
      probability: 1.0