database: h2
management.endpoints.web.exposure.include: health, info, refresh
management.endpoint.health.probes.enabled: true
management.endpoint.health.show-details: always
management.endpoint.health.circuitbreakers.enabled: true
#logging & management
logging.level.org.springframework.security: TRACE
logging.level.reactor.netty.http.client: TRACE
#thymeleaf and dev tools



server:
  port:
    8061
app:
  issuer-uri: ${HOST_ISSUER_URI:}
spring:
  profile: dev
  thymeleaf:
    cache: false
  devtools:
    restart:
      exclude: /static/**,/templates/**
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: false
    gateway:
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/uaa/**
          filters:
            - PrefixPath=/api
        - id: account
          uri: lb://account
          predicates:
            - Path=/account/**
          filters:
            - PrefixPath=/api
            - DmFilterFactory=DMSERVICES WORKING IN DEV FOR ACCOUNTS, true, true
        - id: stats
          uri: lb://stats
          predicates:
            - Path=/stats/**
          filters:
            - PrefixPath=/api
            - DmFilterFactory=DMSERVICES WORKING IN DEV FOR STATS, false, true
        - id: noti
          uri: lb://noti
          predicates:
            - Path=/noti/**
          filters:
            - PrefixPath=/api
            - DmFilterFactory=DMSERVICES WORKING IN DEV FOR NOTI, false, true
#resilience4j

gateway:
  circuit-breaker:
    name: gateway-circuit-breaker
    failure-rate-threshold: 50
    minimum-number-of-calls: 5
    slow-call-rate-threshold: 50
    slow-call-duration-threshold-milis: 2000
    wait-duration-in-open-state-milis: 5000
    permitted-number-of-calls-in-half-open-state: 3
    sliding-window-size: 10
    timeout-duration-milis: 10000