
  server:
  port:
    8061
spring:
  security:
    oauth2:
      client:
        registration:
          browserClient:
            provider: auth
            client-id: browserClient
            client-secret: "{bcrypt}$2a$10$RfRD97cQUakYcKRirWsK1exiZOxdVjmYa0hQhx08pAmnhrDPADs4S"
            authorization-grant-types: authorization_code,refresh_token
            client-authentication-method: client_secret_basic
            scope: openid,profile
            redirect-uri: "http://127.0.0.1:8061/login/oauth2/code/browserClient"
        provider:
          auth:
            issuer-uri: http://localhost:9000/api/uaa
  profile: dev
  cloud:
    gateway:
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/uaa/**
          filters:
            - PrefixPath=/api
        - id: account
          uri: lb://account
          predicates:
            - Path=/account/**
          filters:
            - PrefixPath=/api
            - DmFilterFactory=DMSERVICES WORKING IN DEV FOR ACCOUNTS, true, true
        - id: stats
          uri: lb://stats
          predicates:
            - Path=/stats/**
          filters:
            - PrefixPath=/api
            - DmFilterFactory=DMSERVICES WORKING IN DEV FOR STATS, false, true
        - id: noti
          uri: lb://noti
          predicates:
            - Path=/noti/**
          filters:
            - PrefixPath=/api
            - DmFilterFactory=DMSERVICES WORKING IN DEV FOR NOTI, false, true
logging:
  level:
    reactor:
      netty:
        http:
          client: TRACE
    org:
      springframework:
        web: DEBUG
        cloud:
          gateway: DEBUG
