server:
  port:
    8061
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
spring:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - PrefixPath=/api
#        -id: andere dienst
#          filters:
#            - PrefixPath=/api
#            - AuthFilter
logging:
  level:
    org:
      springframework:
        gateway: TRACE