server:
  servlet:
    context-path: /api/noti
  port: 8084
spring:
  profile: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: pepemanso85@gmail.com
    password: daaihaeiqmzrjrdu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:h2:mem:demo
    username: sa
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

backup:
  cron: 0 0 12 * * *
  email:
    subject: "Backup message from Duvi Dmservices Team!"
    text: "Regards, \nDmservices Team."
    attachment: "backup.json"
remind:
  cron: 0 0 0 * * *
  email:
    subject: "Reminder from Dmservices Team!"
    text: "Hey, {0}!\n It's always good to see you, consider coming back soon, your finances do not sleep!\n\nRegards,\nDmservices Team"