server:
  servlet:
    context-path: /api/noti
  port: 8084
spring:
  profile: prod
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://auth-service:9000/api/uaa
      client:
        provider:
          auth:
            issuer-uri: http://auth-service:9000/api/uaa
        registration:
          notiClient:
            provider: auth
            client-id: notiClient
            client-secret: noti
            authorization-grant-type: client_credentials
            scope: openid,email
            client-name: notiService
  mail:
    host: smtp.gmail.com
    port: 587
    username: pepemanso85@gmail.com
    password: daaihaeiqmzrjrdu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://dmservices-database:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
backup:
  cron: 0 0 12 * * *
  email:
    subject: "Backup message from Duvi Dmservices Team! - {0}"
    text: "Regards, \nDmservices Team."
    attachment: "backup.json"
remind:
  cron: 0 0 0 * * *
  email:
    subject: "Reminder from Dmservices Team! - {0}"
    text: "Hey, {0}!\n It's always good to see you, consider coming back soon, your finances do not sleep!\n\nRegards,\nDmservices Team - {1}"