database: h2
management.endpoints.web.exposure.include: health, info, refresh
management.endpoint.health.probes.enabled: true
management.endpoint.health.show-details: always
management.endpoint.health.circuitbreakers.enabled: true
#logging & management
logging.level.org.springframework.security: TRACE

server:
  servlet:
    context-path: /api/noti
  port: 8084
spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  profile: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: pepemanso85@gmail.com
    password: daaihaeiqmzrjrdu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:h2:mem:demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true
  flyway:
    locations: classpath:/db/migration/${database}
backup:
  cron: "*/1 * * * * *"
  email:
    subject: "Backup message from Duvi Dmservices Team!"
    attachment: "backup.json"
remind:
  cron: "*/1 * * * * *"
  email:
    subject: "Reminder from Dmservices Team!"