database: postgres

server:
  servlet:
    context-path: /api/noti
  port: 8084
spring:
  profile: prod
  flyway:
    locations: classpath://db/migration/${database}
  mail:
    host: smtp.gmail.com
    port: 587
    username: pepemanso85@gmail.com
    password: daaihaeiqmzrjrdu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://dmservices-database:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
backup:
  cron: "*/10 * * * * *"
  email:
    subject: "Backup message from Duvi Dmservices Team!"
    attachment: "backup.json"
remind:
  cron: "*/10 * * * * *"
  email:
    subject: "Reminder from Dmservices Team!"
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info