server:
  port: 8085
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:7099/api/auth
      client:
        provider:
          auth:
            issuer-uri: http://localhost:7099/api/uaa
        registration:
          statsClient:
            provider: auth
            client-id: statsClient
            client-secret: stats
            authorization-grant-type: client_credentials
            scope: openid,profile
            client-name: statsService
  datasource:
    url: jdbc:postgresql://statpg:5432
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
