server:
  port: 8085
spring:
  profiles:
    active: "dev"

---

spring:
  profiles: dev
  datasource:
    url: jdbc:h2:file:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL94Dialect

---

spring:
  profiles: prod