server:
  servlet:
    context-path: /api/stats
  port: 8085
spring:
  profile: mem
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9000/api/uaa
      client:
        provider:
          auth:
            issuer-uri: http://localhost:9000/api/uaa
        registration:
          statsClient:
            provider: auth
            client-id: statsClient
            client-secret: stats
            authorization-grant-type: client_credentials
            scope: openid,profile
            client-name: statsService
  datasource:
    url: jdbc:h2:mem:demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: TRACE