server:
  servlet:
    context-path: /api/stats
  port: 8085
spring:
  profile: dev
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:7099/api/auth
#      client:
#        clientId: stat
#        clientSecret: password
#        accessTokenUri: http://localhost:7099/api/auth/oauth2/token
#        authorization-grant-type: client_credentials
#        scope: oidc.profile
  datasource:
    url: jdbc:h2:mem:demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: TRACE