database: h2

server:
  servlet:
    context-path: /api/stats
  port: 8085
spring:
  profile: dev
  datasource:
    url: jdbc:h2:mem:demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  flyway:
    user: sa
    password: password
    url: jdbc:h2:mem:demo
    locations: classpath:db/migration/${database}
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: false
logging:
  level:
    org:
      springframework:
        security: TRACE
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info